### ISSUE TITLE
Can you explain hyper parameters?

### ISSUE THREAD

**Issue by woo1** [JanaldoChen/Anim-NeRF#12]
Thanks for sharing this wonderful work!
As you mentioned in the paper,
"
We set the hyper-parameters as |N (𝑖)| = 4,
𝛿 = 0.2, 𝜆1 = 0.001, 𝜆2 = 0.01 and 𝜆𝑑 = 0.1. We use 512×512
image in all experiments. For training the model, we adopt the
Adam optimizer [52], and it spends about 13 hours on 2 Nvidia
GeForce RTX 3090 24GB GPUs
"
can you specify what the parameter is in the config file?
|N (𝑖)| : batch_size
𝛿 : dis_threshold
𝜆1 : lambda_pose in opt.py
𝜆2 : lambda_pose_smooth in opt.py
𝜆𝑑 : lambda_background

Is this right variables?

**Comment by JanaldoChen** [comment]
|N (𝑖)| is the number of nearest neighbor vertices for given point x in observation space.

**Comment by woo1** [comment]
Thanks a lot
