### ISSUE TITLE
pose refinement or no?

### ISSUE THREAD

**Issue by FebOne1** [JanaldoChen/Anim-NeRF#14]
I noticed that the pose smooth loss is commented out. Does it mean there is no pose refinement? Or adding pose refinement performs worse? Thanks!
https://github.com/JanaldoChen/Anim-NeRF/blob/232d471b4d207175c00bea54377b36c46fd675f8/train.py#L248

**Comment by JanaldoChen** [comment]
Yes, there is pose refinement, the pose parameters is refined by set *optim_body_params: True* in configs/people_snapshot/male-3-casual.yaml. But in the last version, I canceled the pose regularization while added the normal regularization mentioned in https://arxiv.org/pdf/2104.10078.pdf
