### ISSUE TITLE
Support half body or not?

### ISSUE THREAD

**Issue by shenwenhao01** [JanaldoChen/Anim-NeRF#15]
Thanks for your wonderful work!
I wonder if the input video only captures half of a body (e.g. upper torso), will Anim-NeRF reconstruct that part well?
For example, the image below.

<img width="439" alt="截屏2022-03-07 下午4 24 01" src="https://user-images.githubusercontent.com/56423956/156994393-84209dbc-37b6-4ddd-a696-9ac71ad6b9f2.png">

**Comment by JanaldoChen** [comment]
Thank you for you attention to our work! I think it is theoretically possible, but it is very difficult to reconstruct facial expressions, hand movements, because SMPL does not model the face and hands, you can try SMPLX.

**Comment by shenwenhao01** [comment]
Thanks, I'll try.
