### ISSUE TITLE
Is the code of  transformation to canonical  space support for MANO hand models?

### ISSUE THREAD

**Issue by Qingcsai** [JanaldoChen/Anim-NeRF#16]
Hi @JanaldoChen : 
I see you changed some code in ```smplx``` to support for SMPL models, which is great. But I wonder if the code of transformation from observation space to canonical  space support for MANO hand models? Particularly for the code of ```clac_ober2cano_transform()``` and ```get_neighbs()```, do the support for ```smplx``` in this repo?

Thank you for your work again!

**Comment by JanaldoChen** [comment]
Thank you for your attention to our work! Although I didn't try it on mano, I think it also works.

**Comment by Qingcsai** [comment]
Thanks for your reply, I may try it.

**Comment by alvaro-budria** [comment]
> Thanks for your reply, I may try it.

Did you finally try adding the MANO model? Did it help improve the reconstruction?
