### ISSUE TITLE
Rename functions imported from TorchMetrics 

### ISSUE THREAD

**Issue by DuYicong515** [JanaldoChen/Anim-NeRF#17]
Thanks for the great work! TorchMetrics has renamed ssim-> scale_invariant_signal_noise_ratio and psnr-> peak_signal_noise_ratio. The old names are being deprecated in v0.7 and will be removed in v0.8.

https://github.com/PyTorchLightning/metrics/commit/8e9eb8efc0591f3be8602c836e34b19fa6dd9fe7

Maybe the imports and usages can also be update to the new name?  
https://github.com/JanaldoChen/Anim-NeRF/blob/d63bf9e55b22b2e30c42eb78930fb8b373ce6f8e/train.py#L26
https://github.com/JanaldoChen/Anim-NeRF/blob/d63bf9e55b22b2e30c42eb78930fb8b373ce6f8e/train.py#L26

**Comment by JanaldoChen** [comment]
OK, Thanks! I will update it.

**Comment by JanaldoChen** [comment]
I have changed it and updated the evaluator, which is slightly different(I set the data_range=1.0 in psnr).
