### ISSUE TITLE
A question about camera parameters

### ISSUE THREAD

**Issue by Auggst** [JanaldoChen/Anim-NeRF#18]
How to estimate the camera intrinsics K ? In your paper, the camera intrinsics is estimated, but the people snapsshot dataset provide a camera file including camera intrinsics.

**Comment by JanaldoChen** [comment]
We don't estimate the camera intrinsics $K$ directly,  it is converted from a weak perspective projection camera parameters $s, t$ estimated by VIBE. Please see (https://github.com/JanaldoChen/Anim-NeRF/blob/main/tools/convert_vibe.py#:~:text=img.shape%5B%3A2%5D-,camera,-%3D%20%7B) about how to convert vibe parameters. The  script (https://github.com/JanaldoChen/Anim-NeRF/blob/main/tools/people_snapshot.py#:~:text=people_ID%2C%20%27camera.pkl%27))-,camera,-%3D%20%7B). is about how to convert the people snapshot dataset

**Comment by GloryyrolG** [comment]
Hi @JanaldoChen , so if I understood correctly, we will not disentangle the camera global rotation and body root rotation, right? I.e., as below `R = I`, and set all rotation into the body rotation (ignoring coordinate transformations). This is cuz we are working in a monocular setting and do not need to deal with multi-view transformation?  Thx & rgds,

https://github.com/JanaldoChen/Anim-NeRF/blob/1342a9e2d02411a09acecac40ac325f38708b9c9/datasets/anim_nerf_dataset.py#L212
