### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by NeaRBrotheR** [JanaldoChen/Anim-NeRF#20]
I used these command of Visualization: 
`python novel_view.py --ckpt_path checkpoints/male-3-casual/last.ckpt`
`python extract_mesh.py --ckpt_path checkpoints/male-3-casual/last.ckpt`
`python novel_view.py --ckpt_path checkpoints/male-3-casual/last.ckpt --betas_2th -2.0`
`python novel_view.py --ckpt_path checkpoints/male-3-casual/last.ckpt --betas_2th 3.0`
`python novel_pose.py --ckpt_path checkpoints/male-3-casual/last.ckpt`
Both got the same error report. And they can't work.

The error report both like :
> (Anim-NeRF) near@near:~/Github/Anim-NeRF$ python novel_view.py --ckpt_path checkpoints/female-3-casual/last.ckpt --betas_2th -2.0
> WARNING: You are using a SMPL model, with only 10 shape coefficients.
> Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
> Loading model from: /home/near/miniconda3/envs/Anim-NeRF/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
> Traceback (most recent call last):
>   File "novel_view.py", line 146, in <module>
>     system = AnimNeRFSystem.load_from_checkpoint(args.ckpt_path).to(device)
>   File "/home/near/miniconda3/envs/Anim-NeRF/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "/home/near/miniconda3/envs/Anim-NeRF/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 204, in _load_model_state
>     keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)
>   File "/home/near/miniconda3/envs/Anim-NeRF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for AnimNeRFSystem:
> 	Missing key(s) in state_dict: "evaluator.lpips.scaling_layer.shift", "evaluator.lpips.scaling_layer.scale", "evaluator.lpips.net.slice1.0.weight", "evaluator.lpips.net.slice1.0.bias", "evaluator.lpips.net.slice2.3.weight", "evaluator.lpips.net.slice2.3.bias", "evaluator.lpips.net.slice3.6.weight", "evaluator.lpips.net.slice3.6.bias", "evaluator.lpips.net.slice4.8.weight", "evaluator.lpips.net.slice4.8.bias", "evaluator.lpips.net.slice5.10.weight", "evaluator.lpips.net.slice5.10.bias", "evaluator.lpips.lin0.model.1.weight", "evaluator.lpips.lin1.model.1.weight", "evaluator.lpips.lin2.model.1.weight", "evaluator.lpips.lin3.model.1.weight", "evaluator.lpips.lin4.model.1.weight", "evaluator.lpips.lins.0.model.1.weight", "evaluator.lpips.lins.1.model.1.weight", "evaluator.lpips.lins.2.model.1.weight", "evaluator.lpips.lins.3.model.1.weight", "evaluator.lpips.lins.4.model.1.weight". 

Could you please give me some advice to solve this problem ?
Thanks a lot !

**Comment by JanaldoChen** [comment]
Thanks for your attention, Please set ```strict=False```.

**Comment by NeaRBrotheR** [comment]
Thank you for your answer, they can work now!

I want to ask one more question.
How do i use my own custom pose data in python novel_pose.py .
I mean creat the motion capture smpl parameters by my data,the format in the result.pkl  is like the mixamo you provided.

**Comment by JanaldoChen** [comment]
Sorry for the late reply! I suggest you can modify the function```load_mixamo_smpl``` in ```novel_pose.py``` to load the smpl parameters in your result.pkl.

**Comment by NeaRBrotheR** [comment]
It can work now!!! Thanks for your help and suggest.
And,
Could I ask about your trained with which GPU ?

**Comment by JanaldoChen** [comment]
I trained the model on 2 * RTX3090 or 2 * Tesla V100
