### ISSUE TITLE
continue training

### ISSUE THREAD

**Issue by orydatadudes** [JanaldoChen/Anim-NeRF#21]
Thank you for your great work
assuming i trained a model and now i want to continue the training process
so i run train.py file and changed the following :

    train_resume = True
    train_ckpt_path = "checkpoints/XXX/last.ckpt"

i saw there are two more params to set :
    model_names_to_load = ?
    pretrained_model_requires_grad = ? 

what should be the value of them ?
there is any thing else i need to change?

thanks

**Comment by JanaldoChen** [comment]
Thanks for your attention!
For continuing the training process, you should set ```train.resume=True``` and ```train.ckpt_path='xxx.ckpt'. ```

For finetuning or load some pretrained models, you should set ```train.model_names_to_load = ['anim_nerf']```, ```train.ckpt_path='xxx.ckpt'.```  and ```train.pretrained_model_requires_grad = False```

**Comment by orydatadudes** [comment]
thanks for the quick  response 
 i have two question to clarify your answer 
1.
 if i continue training that mean setting:
 train_resume = True   and    train_ckpt_path = "checkpoints/XXX/last.ckpt"
 i have to set train.model_names_to_load = ['anim_nerf'], otherwise error arise  :
train.py lines 433

    if cfg.train.ckpt_path is not None:
        for model_name in cfg.train.model_names_to_load:
            load_ckpt(getattr(system, model_name), cfg.train.ckpt_path, model_name)
            for param in getattr(system, model_name).parameters():
                param.requires_grad = cfg.train.pretrained_model_requires_grad
 
2. i don't have to change train.pretrained_model_requires_grad = True ?


thank you

**Comment by JanaldoChen** [comment]
It seems that the number of training frames has changed. In our method, we need to optimize the smpl parameters for each training frame, so if you want to continue training, please make sure that the training frames should not change.
