### ISSUE TITLE
How to generate textured 3D models?

### ISSUE THREAD

**Issue by wusidong** [JanaldoChen/Anim-NeRF#22]
Thank you for your great work. I have a question whether the code can generate a textured 3D model. I ran your code and did not generate a textured 3D model.

**Comment by wusidong** [comment]
> Thank you for your great work. I have a question whether the code can generate a textured 3D model. I ran your code and did not generate a textured 3D model.

I only get a geometry model.

**Comment by JanaldoChen** [comment]
Sorry for the delay,  our method does not directly obtain the texture map from the neural radiance field.

**Comment by JunfengLiu1** [comment]
Not directly obtain....Is there any way we can get texture map?
