### ISSUE TITLE
How to compute the evaluation index such as P2S and Chamfer distance?

### ISSUE THREAD

**Issue by uujianghhh** [JanaldoChen/Anim-NeRF#24]
Hello,thank you for making such wonderful project,and I want to know how to compute the evaluation index such as P2S and Chamfer distance,I would be appreaciate it if you can tell me,thank you!

**Comment by JanaldoChen** [comment]
You can use the ```chamfer_distance``` and ```point_mesh_face_distance``` in ```pytorch3d.loss``` to compute the metrics.
