### ISSUE TITLE
Wild Focal = 2000?

### ISSUE THREAD

**Issue by GloryyrolG** [JanaldoChen/Anim-NeRF#27]
Hi @JanaldoChen @woo1  et al.,

May I ask if we intend to empirically use a slightly smaller focal len which is assumed to be closer to the in-the-wild deployment? Thx & rgds,
https://github.com/JanaldoChen/Anim-NeRF/blob/1342a9e2d02411a09acecac40ac325f38708b9c9/tools/convert_vibe.py#L34

**Comment by JanaldoChen** [comment]
Due to using the weak perspective projection model [s, tx, ty] by VIBE, there is no true image camera intrinsic. So you can use an empirical focal parameter as you want, just keep the projection right.
