### ISSUE TITLE
running on custom video

### ISSUE THREAD

**Issue by fyviezhao** [JanaldoChen/Anim-NeRF#5]
Hi, thanks for sharing this wonderful work! In the currently released code, the people_snapshot dataset already has the associated smpl and camera parameters, which is easy to get started with. Could you further give some instruction on how to prepare these necessary inputs for a custom monocular video (assuming this video is similar to those in people_snapshot)? Something like a `python -m tools.custom_video --data_root ${path_to_custom_video}` along with a `python -m tools.prepare_template_for_custom_video` would be much appreciated.

**Comment by JanaldoChen** [comment]
For the smpl params of a custom video, you can get it using videoavators(https://github.com/thmoa/videoavatars) like people snapshot dataset or VIBE(https://github.com/mkocabas/VIBE). I'm currently working on the custom video code, which will be released in the next few days!

**Comment by fyviezhao** [comment]
Sounds great! Thanks.

**Comment by JanaldoChen** [comment]
I have updated the scripts about iper datasets and custom datasets, you can try it.
