### ISSUE TITLE
training error - AssertionError: Invalid type <class 'NoneType'> for key cam_IDs

### ISSUE THREAD

**Issue by woo1** [JanaldoChen/Anim-NeRF#7]
Hi, Thanks for sharing this wonderful code!
When I try training with this command.
`
python train.py --cfg_file configs/people_snapshot/male-3-casual.yml
`
this error raises

> Traceback (most recent call last):
>   File "train.py", line 425, in <module>
>     cfg = get_cfg()
>   File "/Anim-NeRF/config.py", line 105, in get_cfg
>     cfg = get_default_config()
>   File "/Anim-NeRF/config.py", line 52, in get_default_config
>     cfg.train.cam_IDs = None
>   File "/Anim-NeRF/venv/lib/python3.7/site-packages/yacs/config.py", line 158, in __setattr__
>     type(value), name, _VALID_TYPES
>   File "/Anim-NeRF/venv/lib/python3.7/site-packages/yacs/config.py", line 521, in _assert_with_logging
>     assert cond, msg
> AssertionError: Invalid type <class 'NoneType'> for key cam_IDs; valid types = {<class 'bool'>, <class 'float'>, <class 'tuple'>, <class 'int'>, <class 'list'>, <class 'str'>}

This error did not raised yesterday.
How can I fix it?

**Comment by Omri-CG** [comment]
How is this issue solved?

**Comment by JanaldoChen** [comment]
> How is this issue solved?

Did you download the training data male-3-causal.zip (https://drive.google.com/drive/folders/1iXD2CShfcjk8fxUAC0VmTdiKeDz-DOc8?usp=sharing), unzip it, and put it in the folder data/people_snapshot?

**Comment by Omri-CG** [comment]
No, I am actually trying to train on my own data (I ran the preparation steps as you mentioned in the `README.md`).
Created my own config file based on the one of male-3-causal and recieving the error above.

**Comment by Omri-CG** [comment]
Solved it - apparently `yacs` added support for `NoneType` at version 0.1.8. So it is essential for this code to work. Better state in your requirements file. 

https://github.com/rbgirshick/yacs/commit/e3b6c5a5d1673ad63779487131ff77c2e185fa5e#diff-687c4b0ca21c454d60648452c71a097c7ed3356daa52792dfa3ee2bd489f8c4f

**Comment by JanaldoChen** [comment]
OK, Thanks! I will fix this bug.
