### ISSUE TITLE
Uploading mixamo mocap 

### ISSUE THREAD

**Issue by Omri-CG** [JanaldoChen/Anim-NeRF#9]
Hi, in `novel_pose.py` you are using mocap information from mixamo file. Can you share that file and make it a configurable path?

**Comment by JanaldoChen** [comment]
I have uploaded the mixamo mocap smpl parameters, you can download it from https://drive.google.com/drive/folders/1iXD2CShfcjk8fxUAC0VmTdiKeDz-DOc8?usp=sharing.

**Comment by Omri-CG** [comment]
Thanks!
